// Tailwind CSS Configuration
// Design tokens are defined inline to avoid TypeScript import issues

const tokens = {
	colors: {
		primary: {
			50: '#eef2ff',
			100: '#e0e7ff',
			200: '#c7d2fe',
			300: '#a5b4fc',
			400: '#818cf8',
			500: '#6366f1',
			600: '#4f46e5',
			700: '#4338ca',
			800: '#3730a3',
			900: '#312e81',
		},
		secondary: {
			50: '#faf5ff',
			100: '#f3e8ff',
			200: '#e9d5ff',
			300: '#d8b4fe',
			400: '#c084fc',
			500: '#a855f7',
			600: '#9333ea',
			700: '#7e22ce',
			800: '#6b21a8',
			900: '#581c87',
		},
		success: {
			50: '#ecfdf5',
			100: '#d1fae5',
			200: '#a7f3d0',
			300: '#6ee7b7',
			400: '#34d399',
			500: '#10b981',
			600: '#059669',
			700: '#047857',
			800: '#065f46',
			900: '#064e3b',
		},
		warning: {
			50: '#fffbeb',
			100: '#fef3c7',
			200: '#fde68a',
			300: '#fcd34d',
			400: '#fbbf24',
			500: '#f59e0b',
			600: '#d97706',
			700: '#b45309',
			800: '#92400e',
			900: '#78350f',
		},
		error: {
			50: '#fef2f2',
			100: '#fee2e2',
			200: '#fecaca',
			300: '#fca5a5',
			400: '#f87171',
			500: '#ef4444',
			600: '#dc2626',
			700: '#b91c1c',
			800: '#991b1b',
			900: '#7f1d1d',
		},
		neutral: {
			50: '#f8fafc',
			100: '#f1f5f9',
			200: '#e2e8f0',
			300: '#cbd5e1',
			400: '#94a3b8',
			500: '#64748b',
			600: '#475569',
			700: '#334155',
			800: '#1e293b',
			900: '#0f172a',
		},
	},
	typography: {
		display: { size: '48px', lineHeight: '56px', weight: 700 },
		h1: { size: '36px', lineHeight: '44px', weight: 700 },
		h2: { size: '24px', lineHeight: '32px', weight: 600 },
		h3: { size: '20px', lineHeight: '28px', weight: 600 },
		bodyLarge: { size: '16px', lineHeight: '24px', weight: 400 },
		body: { size: '14px', lineHeight: '20px', weight: 400 },
		caption: { size: '12px', lineHeight: '16px', weight: 400 },
	},
	spacing: {
		xs: '4px',
		sm: '8px',
		md: '12px',
		lg: '16px',
		xl: '24px',
		'2xl': '32px',
		'3xl': '48px',
		'4xl': '64px',
	},
	borderRadius: {
		sm: '8px',
		md: '12px',
		lg: '16px',
		xl: '24px',
	},
	shadows: {
		sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
		md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
		lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
		xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
		'2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
	},
	animations: {
		duration: {
			fast: '150ms',
			normal: '200ms',
			slow: '300ms',
		},
		easing: {
			easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
			easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
			spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
		},
	},
}

module.exports = {
	content: [
		'./pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./components/**/*.{js,ts,jsx,tsx,mdx}',
		'./app/**/*.{js,ts,jsx,tsx,mdx}',
		'./lib/**/*.{js,ts,jsx,tsx,mdx}',
	],
	darkMode: 'class',
	theme: {
		screens: {
			xs: '480px',
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			'2xl': '1536px',
			'3xl': '1920px',
		},
		extend: {
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				// Design system tokens
				primary: {
					...tokens.colors.primary,
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					...tokens.colors.secondary,
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				sidebar: {
					DEFAULT: 'hsl(var(--sidebar-background))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
				},
				chart: {
					1: 'hsl(var(--chart-1))',
					2: 'hsl(var(--chart-2))',
					3: 'hsl(var(--chart-3))',
					4: 'hsl(var(--chart-4))',
					5: 'hsl(var(--chart-5))',
				},
				success: tokens.colors.success,
				warning: tokens.colors.warning,
				error: tokens.colors.error,
				neutral: tokens.colors.neutral,
				// Legacy colors for compatibility
				cream: '#FAFAF8',
				'cream-dark': '#F5F5F3',
				sage: '#4A7C6F',
				'sage-light': '#5A9A8A',
				'sage-dark': '#3A6258',
				clay: '#C17B5F',
				'clay-light': '#D49175',
				charcoal: '#1A1A1A',
				'charcoal-light': '#2D2D2D',
				'warm-gray': '#6B6B6B',
				'stone': '#E5E5E5',
				'paper': '#FFFFFF',
				'background-light': '#FAFAF8',
				'background-dark': '#1A1A1A',
				'surface-dark': '#252525',
				'surface-light': '#FFFFFF',
				'border-dark': '#2D2D2D',
			},
			fontSize: {
				// Design system typography
				'display': [tokens.typography.display.size, { lineHeight: tokens.typography.display.lineHeight, fontWeight: tokens.typography.display.weight }],
				'h1': [tokens.typography.h1.size, { lineHeight: tokens.typography.h1.lineHeight, fontWeight: tokens.typography.h1.weight }],
				'h2': [tokens.typography.h2.size, { lineHeight: tokens.typography.h2.lineHeight, fontWeight: tokens.typography.h2.weight }],
				'h3': [tokens.typography.h3.size, { lineHeight: tokens.typography.h3.lineHeight, fontWeight: tokens.typography.h3.weight }],
				'body-large': [tokens.typography.bodyLarge.size, { lineHeight: tokens.typography.bodyLarge.lineHeight, fontWeight: tokens.typography.bodyLarge.weight }],
				'body': [tokens.typography.body.size, { lineHeight: tokens.typography.body.lineHeight, fontWeight: tokens.typography.body.weight }],
				'caption': [tokens.typography.caption.size, { lineHeight: tokens.typography.caption.lineHeight, fontWeight: tokens.typography.caption.weight }],
			},
			fontFamily: {
				sans: [
					'var(--font-sans)',
					'ui-sans-serif',
					'system-ui',
					'-apple-system',
					'BlinkMacSystemFont',
					'sans-serif',
				],
				display: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
				body: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
			},
			spacing: {
				// Design system spacing (in addition to Tailwind defaults)
				'xs': tokens.spacing.xs,
				'sm': tokens.spacing.sm,
				'md': tokens.spacing.md,
				'lg': tokens.spacing.lg,
				'xl': tokens.spacing.xl,
				'2xl': tokens.spacing['2xl'],
				'3xl': tokens.spacing['3xl'],
				'4xl': tokens.spacing['4xl'],
				// Provider shell sizing: keeps the native-style mobile nav and sheets
				// consistent without scattering viewport math through components.
				'provider-gutter': 'clamp(0.75rem, 2vw, 1.5rem)',
				'mobile-nav': '4.25rem',
				'mobile-nav-safe': 'calc(4.25rem + env(safe-area-inset-bottom, 0px))',
				'mobile-sheet-gutter': '0.75rem',
				'compact-tap': '2.25rem',
			},
			maxHeight: {
				'mobile-dialog': 'calc(100svh - 6rem)',
				'mobile-sheet': 'calc(100svh - 5rem)',
				'provider-list': 'calc(100dvh - 17rem)',
				'provider-thread': 'calc(100dvh - 12rem)',
			},
			minHeight: {
				'compact-tap': '2.25rem',
				'mobile-field': '2.5rem',
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
				// Design system border radius (prefixed to avoid overriding Tailwind defaults)
				'ds-sm': tokens.borderRadius.sm,
				'ds-md': tokens.borderRadius.md,
				'ds-lg': tokens.borderRadius.lg,
				'ds-xl': tokens.borderRadius.xl,
				'provider-card': '12px',
				'provider-sheet': '18px',
				// Legacy values
				'2xl': '16px',
				'3xl': '24px',
			},
			boxShadow: {
				'xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
				// Design system shadows
				'sm': tokens.shadows.sm,
				'md': tokens.shadows.md,
				'lg': tokens.shadows.lg,
				'xl': tokens.shadows.xl,
				'2xl': tokens.shadows['2xl'],
				// Legacy shadows for compatibility
				'soft': '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04)',
				'soft-md': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)',
				'soft-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04)',
				'elevated': '0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 10px 10px -5px rgba(0, 0, 0, 0.02)',
				'node': '0 2px 4px rgba(0, 0, 0, 0.06)',
				'node-hover': '0 4px 8px rgba(0, 0, 0, 0.08)',
				'provider-surface': '0 1px 2px rgba(15, 23, 42, 0.06), 0 10px 30px rgba(15, 23, 42, 0.06)',
				'mobile-nav': '0 10px 30px rgba(15, 23, 42, 0.16)',
				'mobile-sheet': '0 20px 60px rgba(15, 23, 42, 0.24)',
			},
			zIndex: {
				'nav': '40',
				'modal': '70',
				'toast': '80',
			},
			transitionDuration: {
				// Design system animation durations
				'fast': tokens.animations.duration.fast,
				'normal': tokens.animations.duration.normal,
				'slow': tokens.animations.duration.slow,
			},
			transitionTimingFunction: {
				// Design system easing functions
				'ease-out': tokens.animations.easing.easeOut,
				'ease-in-out': tokens.animations.easing.easeInOut,
				'spring': tokens.animations.easing.spring,
			},
			animation: {
				'fade-in': 'fadeIn 0.2s ease-out',
				'slide-up': 'slideUp 0.3s ease-out',
				'shake': 'shake 0.5s ease-in-out',
			},
			keyframes: {
				fadeIn: {
					'0%': { opacity: '0' },
					'100%': { opacity: '1' },
				},
				slideUp: {
					'0%': { opacity: '0', transform: 'translateY(8px)' },
					'100%': { opacity: '1', transform: 'translateY(0)' },
				},
				shake: {
					'0%, 100%': { transform: 'translateX(0)' },
					'20%': { transform: 'translateX(-6px)' },
					'40%': { transform: 'translateX(6px)' },
					'60%': { transform: 'translateX(-4px)' },
					'80%': { transform: 'translateX(4px)' },
				},
			},
		},
	},
	plugins: [
		require('tailwindcss-animate'),
		require('tailwindcss-safe-area'),
		require('@tailwindcss/typography'),
	],
}
